### ISSUE TITLE
0.15 + 1.19.3 If you once get modifier it will never go off

### ISSUE THREAD

**Issue by variety754** [fzzyhmstrs/gearifiers#2] opened 2023-03-01 05:19 UTC
Modifiers are multiplying. For example, I can put on my boots with racing 100 times and I will get faster and faster each time I put it on. Same works for every modifier of armor, health, damage. In 0.14 there is no mistake.

**Comment by fzzyhmstrs** [comment] 2023-03-01 05:48
I can't replicate this on the latest version in my development environment. I get speed when I add equipment, lose it when I take it off. Are you playing on a certain modpack? Can you give a mod list?

**Comment by chaka996** [comment] 2023-03-01 06:02
Having the same issue here since updating. Happens inconsistently, sometimes I can spam re-equip a piece of gear and the mods will stack, other times it will function normally, and sometimes it seems to only happen upon taking damage after spam-equipping. What's the easiest way to share my modlist with you?

**Comment by variety754** [comment] 2023-03-01 08:11
Yes, of course. I'm playing on my own modpack. I don't know how to correctly send modlist so it'll be docx with names and hyperlinks of mods.
[DreamMods 1.4 Stable modlist.docx](https://github.com/fzzyhmstrs/gearifiers/files/10858536/DreamMods.1.4.Stable.modlist.docx)

**Comment by fzzyhmstrs** [comment] 2023-03-01 12:29
The easiest way for me to see the modlist would be for both of you to share your latest log. It's important that I can see the versions too, which will be in the log. You can find the logs in the `.minecraft` folder under the `logs` subfolder. Here is a guide on getting to the `.minecraft` folder if you need help with that: [https://www.wikihow.com/Access-Your-.Minecraft-Folder-on-the-Computer](https://www.wikihow.com/Access-Your-.Minecraft-Folder-on-the-Computer)

@chaka996 if you are playing on a published modpack, you can also send me the link to that and it will help.

Another player has reported an issue with attack damage on the discord, but also confirmed that it does not happen if you only have Gearifiers and it's dependencies installed. This makes me think there is an interaction between two or more mods happening.

Can you also let me know: Did you update any other mods alongside Gearifiers?

**Comment by fzzyhmstrs** [comment] 2023-03-01 12:45
I'm also having a hard time understanding that _just_ the latest version of Gearifiers alone would be causing the issue. Nothing in the latest update dealt with attributes. This is why I'd like to know if anything else was updated alongside Gearifiers.

At least I would like to know the **Gear Core** version being used, and if it was updated alongside the Gearifiers update, or has been the latest version been included with both 0.1.4 and 0.1.5 in testing.

**Comment by fzzyhmstrs** [comment] 2023-03-01 16:55
Related discord conversation for reference: [https://discord.com/channels/1001956883986391190/1073814553231630346](https://discord.com/channels/1001956883986391190/1073814553231630346)

**Comment by chaka996** [comment] 2023-03-01 20:27
Away from PC right now, but I did update other mods alongside gearifiers. Supplementaries, MC Dungeons Armor, Creeper Overhaul, Blockus, Plenty of Armors, The Bumblezone, Moonlight lib were all updated at the same time. I also did update gear core alongside gearifiers, am on version 0.1.4 on minecraft version 1.19.2. Will send full log later if you need.

**Comment by variety754** [comment] 2023-03-01 22:12
[latest.log](https://github.com/fzzyhmstrs/gearifiers/files/10865687/latest.log)
Here it is

**Comment by variety754** [comment] 2023-03-01 22:14
And yes, I was updating both core and main mode

**Comment by variety754** [comment] 2023-03-02 00:08
Carrot set from Mythic Metals could be used. That's how I learned about mistake. And somehow it even works with netherite armor, randomly

**Comment by AllyJaxx** [comment] 2023-03-02 04:11
This has been happening to me on 1.19.2, not a 1.19.3 only issue.

**Comment by fzzyhmstrs** [comment] 2023-03-02 12:30
Allyjaxx, can you post your modlist or modpack link as well?

**Comment by AllyJaxx** [comment] 2023-03-03 01:32
I'm using over 200 mods, so I don't think thats the best idea, but I did run some testing with just this mod and experienced it still.

**Comment by variety754** [comment] 2023-03-03 01:57
So what I learned is that bugs is both in Gear Core and Gearifiers. One causing armor problems, other HP problems. I tried to experiment updating only one mod at the time. When Gearifiers 0.20 is installed with Gear Core 0.13 there is no armor problem, but there is still hp problem. If I will update Gear Core to 0.14, armor problem will return.

**Comment by fzzyhmstrs** [comment] 2023-03-03 14:19
@AllyJaxx If you are seeing it with just Gearifiers and Gear core, that's something that hasn't been reported before and I can just check on Gearifiers itself. (Most likely gear core actually). I haven't been able to replicate it myself with just Gearifiers yet, so I'll have to try some more. Are you seeing it with certain situations?

**Comment by chaka996** [comment] 2023-03-03 23:57
Here's an example of the issue being recreated in a flat singleplayer world with my entire modlist loaded:
https://streamable.com/5zd2tf

Here's an example of affixes stacking upon taking damage and remaining in effect even with the armor un-equipped:
https://streamable.com/repxjq

Again both of these revert upon re-logging. Attached is REI log that lists all loaded mods, I thought I included it before when I talked about trying to recreate the issue, just now realized I did not do that.

I cannot recreate in a single player world with only gearifiers + dependencies + generic client side performance suite loaded.
I've been going down the list of mods that are in both my list and @variety754 's list, but have not yet been able to find a specific mod that allows the issue to be recreated when loaded alone with gearifiers.

[rei.log](https://github.com/fzzyhmstrs/gearifiers/files/10886982/rei.log)

**Comment by chaka996** [comment] 2023-03-04 00:18
In the exact same modlist as in those examples, changing gear core to version 0.1.3 and changing nothing else results in me not being able to recreate the issue. I don't know how helpful that is but that has to narrow it down somewhat right?

**Comment by fzzyhmstrs** [comment] 2023-03-04 00:32
@chaka996  That mod that is showing you all the attributes, is that PlayerEx? that might be a good candidate for a conflict right there.

I've made a set of updates to both mods, can you or someone else please try to replicate the issues with the new versions and let me know if they are resolved or not?

[Gearifier_Gear-Core_Updates.zip](https://github.com/fzzyhmstrs/gearifiers/files/10887075/Gearifier_Gear-Core_Updates.zip)

**Comment by fzzyhmstrs** [comment] 2023-03-04 00:41
Also yes, the hint from preivous comments about downgrading versions did clue me into a possible fix

**Comment by chaka996** [comment] 2023-03-04 00:51
Issue still present in the new versions. I'll see if removing PlayerEx changes anything.

**Comment by chaka996** [comment] 2023-03-04 00:58
No change, issue still present

**Comment by fzzyhmstrs** [comment] 2023-03-04 01:00
-_______-

I haven't still been able to replicate this. I'll sit there for 5 minute equipping and un-equipping a helmet with racing and nothing; the speed comes on and off exactly as expected

**Comment by chaka996** [comment] 2023-03-04 01:03
Yeah its very odd. I cant find any combination of specific mods that lets me recreate it. I'll start disabling a mod at a time on my main list and see if i can narrow it down any.

**Comment by variety754** [comment] 2023-03-04 01:04
> -_______-
> 
> I still haven't been able to replicate this. I'll sit there for 5 minute equipping and un-equipping a helmet with racing and nothing; the speed comes on and off exactly as expected

Will my video footage help to replicate this or it's useless?

**Comment by fzzyhmstrs** [comment] 2023-03-04 01:10
I don't think another video will help me more. I can clearly see the issue that is occurring, but I have no idea what internally is causing it,,, because I can repeat the steps exactly and never get similar results so far

I just tried a piece of gear with Racing like in the video from chaka996, and couldn't cause the issue at all, clicking like a madman to equip and un-equip the gear as fast as possible.

The fact that removing boots without any modifiers causes the modifiers from another piece of gear to be applied is completely mystifying.

**Comment by variety754** [comment] 2023-03-04 01:12
There is even a rare issue when all the weapons you holded combining damage for any of your punch, even with an empty hand. I can't replicate it, it was working only in my main survival world for some reason.

**Comment by fzzyhmstrs** [comment] 2023-03-04 01:13
I'm trying to run an instance of DarkRPG to see if I can at least see _something_ from my end.

**Comment by variety754** [comment] 2023-03-04 01:13
> I don't think another video will help me more. I can clearly see the issue that is occurring, but I have no idea what internally is causing it,,, because I can repeat the steps exactly and never get similar results so far
> 
> I just tried a piece of gear with Racing like in the video from chaka996, and couldn't cause the issue at all, clicking like a madman to equip and un-equip the gear as fast as possible.
> 
> The fact that removing boots without any modifiers causes the modifiers from another piece of gear to be applied is completely mystifying.

However, I already made it waiting for the answer, so if you want you can watch it, here is the link: https://youtu.be/Re0nOn6IynE

**Comment by chaka996** [comment] 2023-03-04 01:16
With just these mods loaded, with the newer versions, affixes wont stack upon receiving damage. With version 0.1.4 of gc and version 0.2.0 of gearifiers instead, taking damage does cause certain affixes to stack, like armour.

[rei.log](https://github.com/fzzyhmstrs/gearifiers/files/10887171/rei.log)

**Comment by fzzyhmstrs** [comment] 2023-03-04 01:17
the health I think is a vanilla bug. But yes the issue with the racing is clear. Only the innate attributes are being removed for some reason, none of the ones added by modifiers

**Comment by variety754** [comment] 2023-03-04 01:18
> the health I think is a vanilla bug. But yes the issue with the racing is clear. Only the innate attributes are being removed for some reason, none of the ones added by modifiers

Well, with 0.13 Core 0.14 Main Mode there is none of these issues. I don't know what you mean by saying vanilla bug

**Comment by chaka996** [comment] 2023-03-04 01:19
> > the health I think is a vanilla bug. But yes the issue with the racing is clear. Only the innate attributes are being removed for some reason, none of the ones added by modifiers
> 
> Well, with 0.13 Core 0.14 Main Mode there is none of these issues. I don't know what you mean by saying vanilla bug

Health boost is really buggy in vanilla. If you take damage after removing the carmot armour, the hearts that shouldnt be there will usually fix themselves.

**Comment by fzzyhmstrs** [comment] 2023-03-04 01:21
Well it's gratifying that my update has done _something_. This stands out to me as a potential issue:

![image](https://user-images.githubusercontent.com/72876796/222867910-3537f8c3-7207-408f-aa6e-1ebe71c314e8.png)

**Comment by chaka996** [comment] 2023-03-04 01:31
Hmm. That's being loaded by something else. I'm not sure what. lol

**Comment by chaka996** [comment] 2023-03-04 01:38
Mythic Metals, Heartbond, and Show Me What You Got all include additional entity attributes.

**Comment by fzzyhmstrs** [comment] 2023-03-04 01:39
Hmm... maybe.. if you add those three in can you start replicating it?

So far I haven't been able to replicate even in DarkRPG, which has been brought up before as having the issue.

**Comment by chaka996** [comment] 2023-03-04 01:42
Yeah im going to check mythic metals by itself first. I don't have heartbond, I just saw that it was in variety's list and confirmed through the author's (apace100) github that it loads their fork of additional entity attributes

**Comment by chaka996** [comment] 2023-03-04 01:49
Okay, mythic metals armors cause affixes to stack upon taking damage

**Comment by chaka996** [comment] 2023-03-04 01:52
It feels like each time I unequip the racing boots, my speed IS reduced, but not to the vanilla run speed. So spam re-equipping slowly raises the floor of run speed until its unmanageably fast. Could it just be a result of weird math?

**Comment by chaka996** [comment] 2023-03-04 01:57
https://streamable.com/h1sfrr

The behaviour is a bit different here from the first examples. If I don't re-equip in between damage instances, the affix doesnt stack. Spam re-equipping without ever taking any damage doesn't seem to do anything.

**Comment by fzzyhmstrs** [comment] 2023-03-04 02:01
Well, that's a bit of progress towards something concrete to investigate

**Comment by fzzyhmstrs** [comment] 2023-03-04 02:25
Heyyy! I can _finally_ replicate this with Mythic Metals added into my debug pack!! No armor being worn:
![image](https://user-images.githubusercontent.com/72876796/222870981-88c97bed-6687-4b49-bdef-08239a2d1beb.png)

**Comment by fzzyhmstrs** [comment] 2023-03-04 02:49
I can replicate without taking damage using Legendary modifiers on leather pants. Bulwark on Ametrine is _not_ stacking. It does seem like speed in particular is causing an issue somehow.
* Legendary: Attack Speed, Damage, Armor, Health, Speed, Durability
* Racing: Speed
* Bulwark: Armor, Armor Toughness

**More importantly: I can replicate after removing Mythic Metals, extracting AdditionalEntityAttrbiutes, and installing just AEA without MM.**

**Comment by fzzyhmstrs** [comment] 2023-03-04 03:46
Update, it may in fact be owo-lib causing the weird interaction, as owo was included alongside Mythic Metals.

**Comment by variety754** [comment] 2023-03-04 05:01
Cool! I glad we found where issue came from. Now we can close this issue?

**Comment by fzzyhmstrs** [comment] 2023-03-04 05:15
I'll mark it as closed once I work out how to solve it with glisco

**Comment by fzzyhmstrs** [comment] 2023-03-04 17:21
Issue should be resolved in Gear Core 0.1.5 and Gearifiers 0.2.1. If issues persist, please feel free to open a new issue.

**Closed by fzzyhmstrs** 2023-03-04 17:21 UTC

**Comment by variety754** [comment] 2023-03-04 22:17
Everything is working! Thank you very much, fzzy. Also I very like all of your mods for 1.19.3 Fabric and all of them are downloaded in my modpack. Your ideas and effort you put in them is incredible. Best luck!
